### ISSUE TITLE
OpenBSD binary build

### ISSUE THREAD

**Issue by sreboot** [hashicorp/packer-plugin-triton#15]
There used to be also an OpenBSD binary download for this plugin - are there any issues preventing OpenBSD builds atmo?

**Comment by nywilken** [comment]
Will be handled by https://github.com/hashicorp/packer-internal-issues/issues/40

**Comment by lbajolet-hashicorp** [comment]
Hey @sreboot, we just released v1.0.2, which now compiles for OpenBSD (and also NetBSD and Solaris), all future releases will also release for these platforms.

Thanks for reporting the problem, we can close this when you confirm this is OK for you?

**Comment by sreboot** [comment]
Thank you.
